name: CI
on:
  push:
    branches:
      - main
      - dev
      - test
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Git LFS install and pull
        run: |
          git lfs install
          git lfs fetch --all
          git lfs pull
      - name: Build and run tests with Docker
        run: |
          docker build -t playwright-tests .
          docker run playwright-tests
